# Generated by Django 5.2 on 2025-05-02 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropDiseasePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='crop_disease/%Y/%m/%d/')),
                ('user_description', models.TextField(max_length=300, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(max_length=10, null=True)),
                ('disease_category', models.CharField(max_length=50)),
                ('characteristics', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
